Sprint9 Домашнее задание
AshZoom/MyMediaPlayer pull request #2
Opened 2023-02-23 17:29 UTC by AshZoom

MyMediaPlayer Sprint9 homework (добавил Styles,SwitchCompat, экраны в DarkMode, текстовые строки на 2-х языках Strings (en and ru); на экране Настройки добавил действия по клику на иконки-1)Share_app (вызывается стандартный диалог),2)Support (подгружается почта по умолчанию и появляются адреса +тема письма+сообщение) и 3)User_agreement (загружается старница Яндекс практимум в браузере), изменил файл SearchActivity.kt (добавил EditText и TextWatcher, добави сохранение текста в строке ввода при повороте экрана). 
Пока не сделал: поля в background у EditText не скруглены (сделал отдельный стиль в res/drawable, но не смог сделать правильное форматирование совместно с кнопкой **X**.

2023-02-24 15:28 UTC, NoDopezzz requested changes

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        //findViewById<Button>(R.id.button_arrow_back_searching).setOnClickListener { finish() }
⏫ Кажется забыл удалить комментарий с мертвым кодом. Обычно стоит в комментариях указывать информацию, которая поясняет определенную часть кода. Также часто разработчики комментируют ненужную часть кода, но чтобы ее в дальнейшем удалить

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +import android.R
⏫ Можно заменить `import` класса `R` из стандартного `package` `android` на `import` класса `R` из твоего `package`: 
`import com.practicum.mymediaplayer.R`

В таком случае, у тебя появится доступ ко всем ресурсам твоего приложения без необходимости прописывать `com.practicum.mymediaplayer.R...`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        val inputTextSearch =
⏫ После исправления предыдущего комментария часть `com.practicum.mymediaplayer.` можно будет удалить

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    fun View.hideKeyboard() {
✅ Отличная идея воспользоваться функцией расширения для этих целей!

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    fun clearButtonVisibility(s: CharSequence?): Int {
⏫ Данный метод называется `clearButtonVisibility` - но вместо того, чтобы "чистить видимость кнопки" он лишь возвращает значение для установки ее видимости. 
Я бы порекомендовал вынести изменение видимости кнопки в сам метод, а метод переименовать в `changeButtonVisibility`

Правильный нейминг переменных и методов значительно повышают читаемость и качество кода!)

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        var searchTextWatcher = object : TextWatcher {
⏫ `searchTextWatcher` является переменной, которая не требует изменения, поэтому ее можно объявить как `val`

Очень хорошей практикой является всегда объявлять объекты и переменные, которые идейно не предполагают изменения, как `read-only`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    @SuppressLint("MissingInflatedId")
⏫ `@SuppressLint("MissingInflatedId")` не понадобится больше после импорта правильного файла R - `com.practicum.mymediaplayer.R`

Теперь все `@SuppressLint("MissingInflatedId")` в `SearchActivity `можно удалить

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    lateinit var inputTextSearch: EditText
⏫ Стоит помнить о модификаторах доступа и применять правила инкапсуляции. Стоит всегда "прятать внутри" класса функции и переменные, которые нет необходимости использовать "снаружи".

Так `inputTextSearch`, `TEXT_EDITTEXT`, `clearButtonVisibility()` и `hideKeyboard()` стоит объявить с модификатором `private`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        var searchTextWatcher = object : TextWatcher {
Иногда даже **Android Studio** будет подсказывать, как стоит улучшить наш код)
<img width="482" alt="image" src="https://user-images.githubusercontent.com/56832972/221173524-9b265003-0a56-4205-90a2-fb8649513c3d.png">

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +    @SuppressLint("MissingInflatedId")
⏫ Т.к. все нужные идентификаторы верстки были объявлены и найдены, `@SuppressLint("MissingInflatedId")` в данном случае кажется лишним.

Порой, у `AndroidStudio` случаются проблемы и она не может обнаружить объявленный файл лэйаута через `R`. Это может смущать, т.к. в этом случае код становится красным и автокомплит может работать неправильно. Чтобы с таким справиться, достаточно провести несколько действий
1. Перейти на вкладку **Build** и вызвать **Rebuild Project**
2. Перейти на вкладку **File** и вызвать `Invalidate Caches...` -> `Invalidate and Restart`

<img width="506" alt="image" src="https://user-images.githubusercontent.com/56832972/221175608-4e68734a-07ec-48ac-9b4b-6e67eec7cc58.png">

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +        findViewById<ImageView>(R.id.button_share_app).setOnClickListener {
⚠️ Ссылки и сообщения из `SettingActivity` стоит вынести в строковый ресурс `strings.xml` и получать его значение через метод `getString(...)`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +            val shareIntent= Intent(Intent.ACTION_SENDTO)
⏫ Нейминг переменной `shareIntent` в случае кнопок поддержки и соглашения не самые подходящие и могут запутать

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +            val message="Спасибо разработчикам и разработчицам за крутое приложение!"
⏫ Чтобы код сделать еще более чистым и читаемым можно реакции на каждую из кнопок вынести в отдельную функцию. Таким образом, получится 3 функции
- поделиться приложением
- написать разработчику
- открыть пользовательское соглашение

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +        findViewById<ImageView>(R.id.button_support).setOnClickListener {
⏫ Пользователь приложения редко нажимает исключительно на иконки кнопок, скорее он старается нажать на текст.
Стоит подумать, как мы можем увеличить области нажатия, чтобы пользователям нашего приложения оно казалось более отзывчивым!

Можно немного изменить верстку экрана настроек следующим образом: текст кнопки и иконку кнопки обернуть в `FrameLayout`, который и будет принимать нажатия

<img width="383" alt="image" src="https://user-images.githubusercontent.com/56832972/221178067-70362a69-4d67-4f28-a0e5-0367ec204bdb.png">

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        val inputTextSearch =
⚠️ Переменная с именем `inputTextSearch` повторно объявляется внутри метода `onCreate` (за объявление переменной отвечает `val`). Из-за этого переменная `inputTextSearch` объявленная как переменная всего класса на 19 строчке так и остается не проинициализованной. 

Такая ошибка является частой у разработчиков, и получила название **shadowing** переменной. Чтобы это справить достаточно перед `inputTextSearch` убрать `val`.

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +        tools:ignore="ExtraText">
⏫ Данная тема уже объявленна в родительской `ViewGroup` и распространяется на все элементы, которые находятся внутри нее.

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +            android:id="@+id/button_arrow_back_searching"
⚠️  Кнопка "назад" используется в приложении уже на двух экранах: поиска и настроек. Поэтому для нее можно также выделить отдельный стиль

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +            android:layout_width="208dp"
⚠️ Для заголовков на экранах "Поиск" и "Настройки" можно выделить отдельный стиль и вынести туда общие атрибуты

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +        <EditText
⚠️ Вместо `LinearLayout` можно использовать `FrameLayout`, который будет содержать в себе `EditText` и `AppCompatButton`. `FrameLayout` является более производительным `ViewGroup` по сравнению с `LinearLayout`. Кроме того, благодаря `FrameLayout` можно реализовать расположение `AppCompatButton` поверх `EditText` без необходимости устанавливать `weight` у дочерних `View`

Кроме того, это решит проблему с установкой правильного `background` со скругленными краями, которую ты описал в описании ПР

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +            android:shape="rectangle"
⏫ Определение атрибута `android:shape` в данном случае не будет создавать никакого эффекта, можно удалить

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/layout/activity_search.xml
> +            android:visibility="gone" />
⏫ Для кнопок, содержащих только одну иконку, можно использовать `AppCompatImageButton`. С `AppCompatImageButton` можно использовать для установки иконки атрибут `android:src`, который и будет устанавливать его в центре кнопки. Таким образом мы избавимся от необходимости установки `android:paddingStart`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/values-night/styles.xml
> +    <style name="MessageTextStyle">
⏫ Мы можем оставить одинаковые стили лишь в одном файле `values/styles.xml`, а в `values-night` оставить только специфичные для темной темы

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/values/themes.xml
> +    <style name="SettingScreen" parent="Theme.MyMediaPlayer">
⏫ Тема `SettingsScreen` используется для экранов поиска и настроек. Предлагаю переименовать на что-то более подходящее, например `SecondaryScreen`

2023-02-24 15:28 UTC, kirillNay commented on app/src/main/res/values/styles.xml
> +    <style name="ButtonStyle" parent="Widget.MaterialComponents.Button">
⚠️ Стиль кнопки `Widget.MaterialComponents.Button` добавляет элементу едва различимую тень (размером 2dp). Чтобы совсем избавиться от тени следуюет отнаследовать стиль от `Widget.MaterialComponents.Button.UnelevatedButton`

2023-02-24 15:28 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +        <item name="android:foreground">?attr/selectableItemBackground</item>
⚠️ Судя по макетам для кнопок стоит использовать шрифт `ys_display_medium`

<img width="595" alt="image" src="https://user-images.githubusercontent.com/56832972/221212147-2265cee0-3230-4257-8c87-d2ef80adb7b7.png">

2023-02-24 15:28 UTC, NoDopezzz commented on app/src/main/res/values-v26/styles.xml
> +</resources>
⏫ При разработке приложений мы можем определенные ресурсы перенести в папку `values-v26`, чтобы они применялись только для устройств с версией SDK >= 26.

В данном случае в этом нет особой необходимости, потому что стили для устройств с разными SDK не будут отличаться

2023-02-24 15:28 UTC, NoDopezzz commented on app/src/main/res/layout/activity_settings.xml
>              android:layout_width="208dp"
Для заголовка экрана "Настройки" не объявлен стиль. Стоит объединить в один стиль заголовки на экране "Настройки" и "Поиск"

2023-02-24 18:33 UTC, AshZoom commented
Спасибо! Замечания получил. Буду исправлять.

Алексей


пт, 24 февр. 2023 г. в 16:28, Kirill Nayduik ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116848229>:
>
> >      override fun onCreate(savedInstanceState: Bundle?) {
>          super.onCreate(savedInstanceState)
> -        setContentView(R.layout.activity_search)
> +        setContentView(com.practicum.mymediaplayer.R.layout.activity_search)
> +
> +        //findViewById<Button>(R.id.button_arrow_back_searching).setOnClickListener { finish() }
>
> ⏫ Кажется забыл удалить комментарий с мертвым кодом. Обычно стоит в
> комментариях указывать информацию, которая поясняет определенную часть
> кода. Также часто разработчики комментируют ненужную часть кода, но чтобы
> ее в дальнейшем удалить
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116853241>:
>
> > @@ -1,11 +1,98 @@
>  package com.practicum.mymediaplayer
>
> -import androidx.appcompat.app.AppCompatActivity
> +import android.R
>
> ⏫ Можно заменить import класса R из стандартного package android на import
> класса R из твоего package:
> import com.practicum.mymediaplayer.R
>
> В таком случае, у тебя появится доступ ко всем ресурсам твоего приложения
> без необходимости прописывать com.practicum.mymediaplayer.R...
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116854813>:
>
> >      override fun onCreate(savedInstanceState: Bundle?) {
>          super.onCreate(savedInstanceState)
> -        setContentView(R.layout.activity_search)
> +        setContentView(com.practicum.mymediaplayer.R.layout.activity_search)
> +
> +        //findViewById<Button>(R.id.button_arrow_back_searching).setOnClickListener { finish() }
> +        val backButton =
> +            findViewById<Button>(com.practicum.mymediaplayer.R.id.button_arrow_back_searching)
> +        val inputTextSearch =
>
> ⏫ После исправления предыдущего комментария часть
> com.practicum.mymediaplayer. можно будет удалить
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116857657>:
>
> > \ No newline at end of file
> +
> +
> +    fun clearButtonVisibility(s: CharSequence?): Int {
> +        return if (s.isNullOrEmpty()) {
> +            View.GONE
> +        } else {
> +            View.VISIBLE
> +        }
> +    }
> +
> +    fun View.hideKeyboard() {
>
> ✅ Отличная идея воспользоваться функцией расширения для этих целей!
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116861158>:
>
> > \ No newline at end of file
> +
> +
> +    fun clearButtonVisibility(s: CharSequence?): Int {
>
> ⏫ Данный метод называется clearButtonVisibility - но вместо того, чтобы
> "чистить видимость кнопки" он лишь возвращает значение для установки ее
> видимости.
> Я бы порекомендовал вынести изменение видимости кнопки в сам метод, а
> метод переименовать в changeButtonVisibility
>
> Правильный нейминг переменных и методов значительно повышают читаемость и
> качество кода!)
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116863775>:
>
> > +        val backButton =
> +            findViewById<Button>(com.practicum.mymediaplayer.R.id.button_arrow_back_searching)
> +        val inputTextSearch =
> +            findViewById<EditText>(com.practicum.mymediaplayer.R.id.inputTextSearch)
> +        val clearButton =
> +            findViewById<AppCompatButton>(com.practicum.mymediaplayer.R.id.clearTextSearch)
> +
> +        backButton.setOnClickListener {
> +            finish()
> +        }
> +
> +        clearButton.setOnClickListener {
> +            inputTextSearch.setText("")
> +            it.hideKeyboard()
> +        }
> +        var searchTextWatcher = object : TextWatcher {
>
> ⏫ searchTextWatcher является переменной, которая не требует изменения,
> поэтому ее можно объявить как val
>
> Очень хорошей практикой является всегда объявлять объекты и переменные,
> которые идейно не предполагают изменения, как read-only
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116878047>:
>
> > +    }
> +
> +    //TEXT_EDITTEXT -ключ, по которому  будем сохранять и восстанавливать   текст
> +    //inputTextSearch.text.toString() - текст который нужно сохранить
> +    override fun onSaveInstanceState(outState: Bundle) {
> +        super.onSaveInstanceState(outState)
> +        outState.putString(TEXT_EDITTEXT, inputTextSearch.text.toString())
> +    }
> +
> +    //получаем сохранённый текст
> +    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
> +        super.onRestoreInstanceState(savedInstanceState)
> +        inputTextSearch.setText(savedInstanceState.getString(TEXT_EDITTEXT))
> +    }
> +
> +    @SuppressLint("MissingInflatedId")
>
> ⏫ @SuppressLint("MissingInflatedId") не понадобится больше после импорта
> правильного файла R - com.practicum.mymediaplayer.R
>
> Теперь все @SuppressLint("MissingInflatedId") в SearchActivity можно
> удалить
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116878705>:
>
> >
>  class SearchActivity : AppCompatActivity() {
> +    lateinit var inputTextSearch: EditText
>
> ⏫ Стоит помнить о модификаторах доступа и применять правила инкапсуляции.
> Стоит всегда "прятать внутри" класса функции и переменные, которые нет
> необходимости использовать "снаружи".
>
> Так inputTextSearch, TEXT_EDITTEXT, clearButtonVisibility() и
> hideKeyboard() стоит объявить с модификатором private
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116904366>:
>
> >
>
>  class SettingActivity : AppCompatActivity() {
> +    @SuppressLint("MissingInflatedId")
>
> ⏫ Т.к. все нужные идентификаторы верстки были объявлены и найдены,
> @SuppressLint("MissingInflatedId") в данном случае кажется лишним.
>
> Порой, у AndroidStudio случаются проблемы и она не может обнаружить
> объявленный файл лэйаута через R. Это может смущать, т.к. в этом случае
> код становится красным и автокомплит может работать неправильно. Чтобы с
> таким справиться, достаточно провести несколько действий
>
>    1. Перейти на вкладку *Build* и вызвать *Rebuild Project*
>    2. Перейти на вкладку *File* и вызвать Invalidate Caches... -> Invalidate
>    and Restart
>
> [image: image]
> <https://user-images.githubusercontent.com/56832972/221175608-4e68734a-07ec-48ac-9b4b-6e67eec7cc58.png>
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> <https://github.com/AshZoom/MyMediaPlayer/pull/2#discussion_r1116906272>:
>
> >      override fun onCreate(savedInstanceState: Bundle?) {
>          super.onCreate(savedInstanceState)
>          setContentView(R.layout.activity_settings)
>          findViewById<Button>(R.id.button_arrow_back).setOnClickListener { finish() }
>
> +        findViewById<ImageView>(R.id.button_share_app).setOnClickListener {
>
> ⚠️ Ссылки и сообщения из SettingActivity стоит вынести в строковый ресурс
> strings.xml и получать его значение через метод getString(...)
> ------------------------------
>
> In app/src/main/java/com/practicum/mymediaplayer/Se [...]

2023-03-01 20:28 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        //findViewById<Button>(R.id.button_arrow_back_searching).setOnClickListener { finish() }
Исправлено

2023-03-01 20:28 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +import android.R
Исправлено. В процессе написания кода не знал, как это изменить. Теперь стало понятно.

2023-03-01 20:29 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        val inputTextSearch =
Исправлено

2023-03-01 20:29 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    fun View.hideKeyboard() {
Спасибо!

2023-03-01 20:29 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    fun clearButtonVisibility(s: CharSequence?): Int {
Исправлено наименование метода (спасибо за совет!). Изменение видимости кнопки решил пока не вносить, т.к. Возможно в будущем потребуется вызывать метод и для других объектов

2023-03-01 20:32 UTC, AshZoom commented on app/src/main/res/layout/activity_settings.xml
>              android:layout_width="208dp"
Исправлено.Добавлен HeadingTextStyle

2023-03-01 20:33 UTC, AshZoom commented on app/src/main/res/values-v26/styles.xml
> +</resources>
Исправлено. Удалил все папки для SDK 26

2023-03-01 20:33 UTC, AshZoom commented on app/src/main/res/values/styles.xml
> +        <item name="android:foreground">?attr/selectableItemBackground</item>
Исправлено. В начале работы над версткой можно было использовать любой шрифт, а в дальнейшем я не обратил на это внимание. Спасибо!

2023-03-01 20:34 UTC, AshZoom commented on app/src/main/res/values/styles.xml
> +    <style name="ButtonStyle" parent="Widget.MaterialComponents.Button">
Исправлено. на Widget.MaterialComponents.Button.UnelevatedButton. Спасибо!

2023-03-01 20:34 UTC, AshZoom commented on app/src/main/res/values/themes.xml
> +    <style name="SettingScreen" parent="Theme.MyMediaPlayer">
Исправлено на SecondaryScreen.Спасибо за ценное предложение!

2023-03-01 20:35 UTC, AshZoom commented on app/src/main/res/values-night/styles.xml
> +    <style name="MessageTextStyle">
Исправлено.

2023-03-01 20:35 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +            android:visibility="gone" />
Спасибо! Учту при доработке проекта

2023-03-01 20:36 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +            android:shape="rectangle"
Исправлено (удалил аттрибут)

2023-03-01 20:36 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +        <EditText
Исправлено. Заменено на FrameLayout и внесены изменения в дизайн строки ввода (скругленные края)

2023-03-01 20:36 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +            android:layout_width="208dp"
Исправлено. Добавлен новый стиль: HeadingTextStyle

2023-03-01 20:37 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +            android:id="@+id/button_arrow_back_searching"
Исправлено. Добавлен новый стиль: BackButtonStyle

2023-03-01 20:37 UTC, AshZoom commented on app/src/main/res/layout/activity_search.xml
> +        tools:ignore="ExtraText">
Исправлено.

2023-03-01 20:37 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        val inputTextSearch =
Исправлено. Спасибо (не учёл, что переменная уже объявлена, но не проинициализирована)

2023-03-01 20:38 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +        findViewById<ImageView>(R.id.button_support).setOnClickListener {
Спасибо. Пока не исправил- посоветуюсь с наставником.

2023-03-01 20:38 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +            val message="Спасибо разработчикам и разработчицам за крутое приложение!"
Исправлено

2023-03-01 20:38 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +            val shareIntent= Intent(Intent.ACTION_SENDTO)
Исправлено

2023-03-01 20:39 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +        findViewById<ImageView>(R.id.button_share_app).setOnClickListener {
Исправлено (добавлены методы вызова getString())

2023-03-01 20:39 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SettingActivity.kt
> +    @SuppressLint("MissingInflatedId")
Исправлено. Большое спасибо за совет- у меня как раз был такой случай («..в этом случае код становится красным и автокомплит может работать неправильно») и я не знал, как исправить ситуацию , хотя и пробовал делать Rebuild, но не обнулял кэш.

2023-03-01 20:40 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    lateinit var inputTextSearch: EditText
Исправлено

2023-03-01 20:40 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +    @SuppressLint("MissingInflatedId")
Исправлено. Удалил.

2023-03-01 20:41 UTC, AshZoom commented on app/src/main/java/com/practicum/mymediaplayer/SearchActivity.kt
> +        var searchTextWatcher = object : TextWatcher {
Спасибо! Исправлено.

2023-03-02 09:49 UTC, NoDopezzz approved these changes

2023-03-07 21:20 UTC, SeveNChaK commented on app/src/main/java/com/practicum/mymediaplayer/TrackAdapter.kt
> +            .transform(RoundedCorners(10))
⚠️ Здесь радиус задается в пикселях. Поэтому значение из макета (которое мы берем как значение в `dp`) необходимо преобразовать в пиксели.
Удобнее всего будет вынести это значение в ресурсы, а потом достать его здесь: `itemView.resources.getDimensionPixelSize(нужный ресурс)`
Обрати внимание, что в макете он = 2

2023-03-07 21:20 UTC, SeveNChaK commented on app/src/main/java/com/practicum/mymediaplayer/TrackAdapter.kt
> +            .placeholder(com.google.android.material.R.drawable.mtrl_ic_error)
⚠️ Плейсхолдер используй из макета
<img width="91" alt="image" src="https://user-images.githubusercontent.com/22057568/223553978-95bcb693-f893-45e1-9b80-18e980bdec42.png">

2023-03-07 21:20 UTC, SeveNChaK commented on app/src/main/res/layout/song_list_layout.xml
> +            android:layout_width="45dp"
⚠️ В ресурсы

2023-03-07 21:20 UTC, SeveNChaK commented on app/src/main/res/layout/song_list_layout.xml
> +                android:textSize="16dp"
⚠️ Размер текста правильно задавать в `sp`

2023-03-07 21:20 UTC, SeveNChaK commented on app/src/main/res/layout/song_list_layout.xml
> +                    android:textSize="11sp"
⚠️ В ресурсы, так как используется несколько раз

2023-03-09 14:28 UTC, merged